### ISSUE TITLE
feat(trusted-sync): Prometheus Metrics Meta Ticket

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/kona#317]
## Overview

For the `trusted-sync` service to be a worth-while tool for monitoring the integrity of `kona-derive` against live chain data, we will need to add visibility. This ticket serves as an aggregator for all of the metrics that we'd like to observe in `trusted-sync` and `kona-derive`.

### `trusted-sync` metrics

- [x] Overall L1 block processing time, beginning to end
- [x] Current validated L2 safe chain height
- [x] Number of malformed batches
- [x] Binary version (string - useful to display on grafana)

### `kona-derive` metrics

- [x] Frame decoding time (buckets)
- [x] Channel decoding time (buckets)
- [x] Batch decompression time (buckets)
- [x] L1 / L2 / L1 beacon RPC latency (buckets)

**Comment by refcell** [comment]
Closing in favor of individual metric issues that are now part of https://github.com/ethereum-optimism/kona/milestone/5
